language: generic
cache: bundler

# Language
language: php
php:
  - 7.1.9

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction
  - npm i -g npm@6.10.2

install:
  - npm ci

script:
  - npm run production