language: generic
cache: bundler

# Language
language: php
php:
  - 7.1.9

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction
  - npm i -g npm@6.10.2

install:
  - npm ci

script:
  - npm run production

deploy:
  local_dir: build_production # Default static site output dir for Jigsaw
  repo: baliphp/baliphp.github.io # This is the slug of the repo you want to deploy your site to
  target_branch: master # Github pages branch to deploy to (in other cases it can be gh-pages)
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN # This is the authentication which you will setup in the next step in travis-ci dashboard
  email: phpbali@gmail.com
  name: "Komunitas PHPBali"
  on:
    branch: master
